#!/usr/bin/env python3
# Build the shipped classify vocab SEED from the AO3 freeform-tag use counts (data/ao3_vocab.csv,
# `name,uses`, produced by build_ao3_layer.py from the OTW statistics dump).
#
# Why: classify's controlled vocab (defaults/classify_vocab.txt) is a tight hand-curated core, so out of
# the box the classifier can only pick from ~120 terms and under-tags (issue #8). The highest-use AO3
# freeforms ARE the generic, reusable tropes (Fluff, Angst, Slow Burn, Hurt/Comfort…) — a use-count
# threshold cleanly separates them from fandom-specific noise (which never accumulates many uses). We ship
# that frequency-gated slice as a SEPARATE file so load_vocab() = curated core ∪ AO3 seed; the curated file
# stays hand-editable and this one stays regenerable (never hand-edit it — re-run this script).
#
# Maintainer-only: needs data/ao3_vocab.csv (gitignored). The OUTPUT ships in the wheel.
#   uv run python build_classify_seed.py           # regenerate src/scourgify/defaults/classify_vocab_ao3.txt
import csv, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DEF = os.path.join(HERE, "src", "scourgify", "defaults")
SRC = os.path.join(HERE, "data", "ao3_vocab.csv")
OUT = os.path.join(DEF, "classify_vocab_ao3.txt")

THRESHOLD = 20000        # AO3 use-count floor: ~125 terms, roughly doubling the curated core (tune to taste)

# AO3 meta/format/medium/length tags that describe FORM, not content — noise for a content classifier.
META = {"one shot", "drabble", "drabble collection", "podfic", "reading", "pov first person"}
def is_meta(name: str) -> bool:
    return name.strip().lower() in META or name.startswith("Wordcount:") or name.startswith("Podfic")

def main() -> None:
    if not os.path.exists(SRC):
        raise SystemExit(f"{SRC} not found — run build_ao3_layer.py first (needs the OTW dump).")
    curated = {l.strip().lower() for l in open(os.path.join(DEF, "classify_vocab.txt"))
               if l.strip() and not l.startswith("#")}
    rows = [(r["name"], int(r["uses"] or 0)) for r in csv.DictReader(open(SRC))]
    seed, seen = [], set(curated)
    for name, uses in sorted(rows, key=lambda r: -r[1]):          # highest-use first
        if uses < THRESHOLD: break
        if re.search(r"\([^)]*\)\s*$", name): continue           # "(Fandom)" suffix -> fandom-specific
        if is_meta(name): continue                               # format/medium/length meta -> not content
        if name.strip().lower() in seen: continue                # already curated (or a dup) -> skip
        seen.add(name.strip().lower()); seed.append(name.strip())
    with open(OUT, "w") as f:
        f.write("# GENERATED by build_classify_seed.py — do NOT hand-edit (re-run the script; tune via overrides/).\n")
        f.write(f"# AO3 freeform tags with >= {THRESHOLD:,} uses (OTW dump), minus fandom-specific / meta / already-curated.\n")
        f.write("# Merged into the controlled vocab by classify.load_vocab(); trim any with a '-term' line in overrides/classify_vocab.txt.\n")
        for t in seed: f.write(t + "\n")
    print(f"wrote {len(seed)} seed terms (uses >= {THRESHOLD:,}) -> {os.path.relpath(OUT, HERE)}")

if __name__ == "__main__":
    main()
