#!/usr/bin/env python3
"""`scourgify setup` — interactive health check + first-run configuration.

Split out of wrangle.py: it shares nothing with normalization. It shells out to
`calibre-customize` to check the FanFicFare plugin, inspects FFF's per-library prefs for the
known gotchas (fandom-vs-series, include_in_series, newonly protection), queues column-creation
ops, and writes config.toml. Writes funnel through run_writer like everywhere else.
`yes=True` (CLI --yes / non-TTY) takes the recommended default for every prompt."""
import os

from scourgify.common import (user_dir, library, ro_connect, interactive, confirm,
                              run_writer, op_create_column, op_set_pref)

OK, WARN, BAD = "✓", "⚠", "✗"     # status glyphs (plain; no color dependency)

# The columns a healthy library has: the engine's 5 + the two datetime markers staleness and
# classify --incremental key off. Module-level because "column health" is a NUMBER other surfaces
# quote (the wizard header, the plugin's Inspect, B6.1's dashboard) and they must all count the
# same 7 things — the source function is named, never re-listed at the call site.
REC = [("#fandoms", "Fandoms", "text", True), ("#characters", "Characters", "text", True),
       ("#relationships", "Relationships", "text", True), ("#genres", "Genres", "text", True),
       ("#status", "Status", "text", False), ("#updated", "Updated", "datetime", False),
       ("#wrangled", "Wrangled", "datetime", False)]


def write_config(colmap: dict, beh: dict | None = None) -> None:
    b = beh or {}                                     # preserve existing toggles on re-run; defaults on first run
    bo = lambda k, d: "true" if b.get(k, d) else "false"
    sv = lambda k, d: b.get(k, d)
    L = ["# scourgify configuration (generated by `setup`; edit anytime).", "", "[columns]",
         '# FanFicFare field -> Calibre column LABEL. "" disables that field\'s passes.']
    L += [f'{k:<13} = "{colmap.get(k, "")}"' for k in ("fandoms", "characters", "relationships", "genres", "status", "tags")]
    L += ["", "# behavior toggles — opinionated defaults; flip to taste", "[behavior]",
          f"fold_characters  = {bo('fold_characters', True)}     # abbreviation -> full-name defaults (Harry P. -> Harry Potter)",
          f"ascii_only_tags  = {bo('ascii_only_tags', True)}     # transliterate non-ASCII tags to plain ASCII",
          f'au_as            = "{sv("au_as", "genre")}"  # where Alternate Universe lands: "genre" or "tag"',
          f'crossover_as     = "{sv("crossover_as", "genre")}"',
          f'reincarnation_as = "{sv("reincarnation_as", "genre")}"',
          f'time_travel_as   = "{sv("time_travel_as", "genre")}"',
          f"fold_ratings     = {bo('fold_ratings', False)}    # Erotica->Smut, Adult->Mature",
          f"keep_categories  = {bo('keep_categories', True)}     # keep Multi/Gen/F-M tags (false drops them)",
          f'tropes_as        = "{sv("tropes_as", "tag")}"    # fold recognized tropes (SI/OC, Fix-It…) into #genres? "genre" or "tag"',
          "", "[overrides]",
          "# folder of user files (same formats as defaults/) that extend & win over the defaults",
          'dir = "overrides"', ""]
    os.makedirs(user_dir(), exist_ok=True)
    open(os.path.join(user_dir(), "config.toml"), "w").write("\n".join(L))


def setup(cfg: dict, yes: bool = False) -> None:
    import subprocess, shutil, json as _json
    asking = interactive() and not yes
    def _ask(prompt: str, default: bool = True) -> bool:
        """y/n prompt; off a TTY (pipe / CI / --yes) take the recommended default instead of blocking."""
        return confirm(prompt, default) if asking else default
    print("=" * 64); print("  scourgify — setup & health check"); print("=" * 64)
    if not asking: print("(non-interactive — taking recommended defaults; run in a terminal to choose per item)")
    ops = []                                          # column/pref writes queued here, applied via calibre-debug at the end
    con = ro_connect()

    # [1] library
    print("\n[1] Library");  print(f"  {OK} metadata.db  ({library()})")

    # [2] FanFicFare: installed? configured? known gotchas?
    print("\n[2] FanFicFare")
    try:
        out = subprocess.run(["calibre-customize", "-l"], capture_output=True, text=True, timeout=30).stdout if shutil.which("calibre-customize") else ""
        installed = ("fanficfare" in out.lower()) if out else None
    except Exception: installed = None
    print(f"  {OK} plugin installed" if installed else
          f"  {BAD} plugin NOT installed (Calibre → Preferences → Plugins → Get new plugins → FanFicFare)" if installed is False else
          f"  {WARN} couldn't query plugins (continuing)")
    row = con.execute("SELECT val FROM preferences WHERE key='namespaced:FanFicFarePlugin:settings'").fetchone()
    settings = _json.loads(row[0]) if row else {}
    fff = settings.get("custom_cols") or {}
    if not settings:
        print(f"  {WARN} no FanFicFare config for this library yet — configure FFF + import a story, then re-run setup")
    else:
        print(f"  {OK} configured — Calibre column ← FFF field:")
        for col, fld in sorted(fff.items()): print(f"        {col:16} ← {fld}")
        ini = settings.get("personal.ini", ""); no = settings.get("custom_cols_newonly", {}) or {}
        issues = []
        if fff.get("#fandoms") == "series": issues.append("#fandoms ← series  (fandom-vs-series gotcha: fandoms land in the numbered Series field)")
        if any(l.strip().lower() == "include_in_series:category" for l in ini.splitlines()): issues.append("personal.ini: include_in_series:category  (stuffs the fandom into Series)")
        if no.get("#genres") is not True: issues.append("#genres not newonly-protected  (a metadata re-fetch would re-pollute your cleaned genres)")
        for i in issues: print(f"  {WARN} {i}")
        if not issues: print(f"  {OK} config looks correct (no known gotchas)")
        elif _ask("  → Fix these now (map #fandoms←category, drop include_in_series, protect #genres)?"):
            import copy; s = copy.deepcopy(settings)
            s["personal.ini"] = "\n".join(l for l in s.get("personal.ini", "").splitlines() if l.strip().lower() != "include_in_series:category")
            if fff.get("#fandoms") == "series": s.setdefault("custom_cols", {})["#fandoms"] = "category"
            s.setdefault("custom_cols_newonly", {})["#genres"] = True
            ops.append(op_set_pref("namespaced:FanFicFarePlugin:settings", s)); print(f"  {OK} queued FanFicFare config fix")

    # [3] columns: the engine's 5 + the datetime markers staleness/classify need
    print("\n[3] Columns")
    have = {"#" + l for (l,) in con.execute("SELECT label FROM custom_columns")} | {"tags"}
    for label, name, dt, mult in REC:
        if label in have: print(f"  {OK} {label}"); continue
        why = "  (staleness + classify --incremental need this)" if label in ("#updated", "#wrangled") else ""
        if _ask(f"  {BAD} {label} missing — create '{name}' ({dt}{', multiple' if mult else ''}){why}?"):
            ops.append(op_create_column(label.lstrip("#"), name, dt, mult)); have.add(label); print(f"      queued {label}")
        else: print(f"      skipped {label}")

    # [4] config.toml column map (FFF field -> our key, else adopt existing labels)
    print("\n[4] config.toml")
    FFF2KEY = {"category": "fandoms", "characters": "characters", "ships": "relationships", "genre": "genres", "status": "status"}
    colmap = {"tags": "tags"}
    for col, fld in fff.items():
        k = FFF2KEY.get(fld)
        if k and col in have: colmap[k] = col
    for label, key in (("#fandoms", "fandoms"), ("#characters", "characters"), ("#relationships", "relationships"), ("#genres", "genres"), ("#status", "status")):
        if not colmap.get(key) and label in have: colmap[key] = label
    write_config(colmap, cfg["behavior"])
    print(f"  {OK} wrote config.toml (behavior toggles preserved):")
    for k in ("fandoms", "characters", "relationships", "genres", "status", "tags"):
        lab = colmap.get(k, ""); print(f"        {k:13} → {lab or '(unset — pass not run for this column)'}")

    # [5] overrides
    from scourgify.overrides import overrides_dir
    odir = overrides_dir(cfg)                     # the one dir resolution (overrides.py owns it)
    print("\n[5] Overrides");  print(f"  {OK} {odir}" if os.path.isdir(odir) else f"  {WARN} no overrides/ dir (optional — add your own maps here; they win over defaults/)")

    if ops:
        print(f"\n[6] Applying {len(ops)} change(s) to Calibre (via calibre-debug)")
        run_writer(ops, tool="setup", scope="columns + prefs")
    print("\n" + "-" * 64)
    print("Setup complete. Next:")
    print("  scourgify audit          # read-only dry-run of all passes")
    print("  scourgify apply --apply  # write changes (Calibre closed; backs up first)")
    print("  scourgify classify --incremental # content-tag new/updated books (cheap)")
